In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
df[df['species'] == 'setosa']

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [7]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
df['species'].map({'versicolor':0,'virginica':1})

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
145    1.0
146    1.0
147    1.0
148    1.0
149    1.0
Name: species, Length: 150, dtype: float64

In [9]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
## Split Dataset into a independent and dependent feature
x = df.iloc[:,:-1]
y = df.iloc[:,:-1]

In [11]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state = 42)

from sklearn.linear_model import LogisticRegression

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
classifier = LogisticRegression

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
parameter = {'penalty':['11','12','elasticnet'],'c':[1,2,3,4,5,6,10,20,30,40,50],'max_iter':[100,200,300]}

In [18]:
classifier_regressor = GridSearchCV(classifier,param_grid = 'parameters',scoring = 'accuracy',cv=5)

In [19]:
print(classifier_regressor)

GridSearchCV(cv=5,
             estimator=<class 'sklearn.linear_model._logistic.LogisticRegression'>,
             param_grid='parameters', scoring='accuracy')

In [20]:
LogisticRegression(penalty='none')

LogisticRegression(penalty='none')

In [21]:
classifier_regressor.get_params()

{'cv': 5,
 'error_score': nan,
 'estimator': sklearn.linear_model._logistic.LogisticRegression,
 'n_jobs': None,
 'param_grid': 'parameters',
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': 'accuracy',
 'verbose': 0}

In [22]:
from sklearn.linear_model import LogisticRegression

classifier_regressor = LogisticRegression()

In [23]:
classifier_regressor.fit(x_train, y_train)

LogisticRegression(penalty='none')

ValueError: y should be a 1d array, got an array of shape (112, 4) instead.

In [ ]:
LogisticRegression(penalty=None)

In [ ]:
from sklearn.linear_model import LogisticRegression

classifier_regressor = LogisticRegression(penalty=None)

classifier_regressor.fit(x_train, y_train)

In [ ]:
print(x_train.shape)
print(y_train.shape)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(classifier_regressor.fit(x_train, y_train)
    x, y, test_size=0.2, random_state=42
)

In [ ]:
print(x_train.shape)
print(y_train.shape)

In [ ]:
classifier_regressor.fit(x_train, y_train)

In [ ]:
print(classifier_regressor.best_params_)

In [ ]:
print(classifier_regressor.best_score_)

In [ ]:
## Prediction
y_pred = classifier_regressor.predict(x_test)

In [ ]:
## Accuracy score
from sklearn.metrics import accuracy_score,classification_report

In [ ]:
score = accuracy_score(y_pred,y_test)

In [ ]:
print(score)

In [ ]:
print(classification_report(y_pred,y_test))

In [ ]:
sns.pairplot(df,hue = 'species')

In [ ]:
df.corr()